[[colors.indexed_colors]]
color = "0xd19a66"
index = 16

[[colors.indexed_colors]]
color = "0xbe5046"
index = 17

[[colors.indexed_colors]]
color = "0x353b45"
index = 18

[[colors.indexed_colors]]
color = "0x3e4451"
index = 19

[[colors.indexed_colors]]
color = "0x565c64"
index = 20

[[colors.indexed_colors]]
color = "0xb6bdca"
index = 21

[colors.bright]
black = "0x545862"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xc8ccd4"
yellow = "0xe5c07b"

[colors.cursor]
cursor = "0xabb2bf"
text = "0x282c34"

[colors.normal]
black = "0x282c34"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xe5c07b"

[colors.primary]
background = "0x101010"
foreground = "0xabb2bf"

[font]
size = 11.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[shell]
args = ["--login", "-c", "tmux attach -t alacritty || tmux new -s alacritty"]
program = "/bin/bash"
