import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[shell]
args = ["--login", "-c", "tmux attach -t alacritty || tmux new -s alacritty"]
program = "/usr/bin/fish"


