
[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal]

[terminal.shell]
program = "/usr/local/bin/fish"
args = ["--login", "-c", "tmux attach -t alacritty || tmux new -s alacritty"]


